version: "3.9"

services:
  web:
    build: .
    container_name: sushi_api
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=manage.py
      - FLASK_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=sushi_db
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: sushi_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sushi_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
