"""Initial

Revision ID: b3c7cf2d134f
Revises: 
Create Date: 2025-08-27 14:40:20.165487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'b3c7cf2d134f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('sushi_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('sushi_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['sushi_item_id'], ['sushi_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('OrderDetails')
    op.drop_table('Customers')
    op.drop_table('Orders')
    op.drop_table('SushiItems')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SushiItems',
    sa.Column('ItemID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('Name', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('Price', sa.DECIMAL(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('Description', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('IsAvailable', mssql.BIT(), server_default=sa.text('((1))'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ItemID', name='PK__SushiIte__727E83EB10F931D0')
    )
    op.create_table('Orders',
    sa.Column('OrderID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('CustomerID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('OrderDate', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.Column('Total', sa.DECIMAL(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['CustomerID'], ['Customers.CustomerID'], name='FK__Orders__Customer__3E52440B'),
    sa.PrimaryKeyConstraint('OrderID', name='PK__Orders__C3905BAFF22D523D')
    )
    op.create_table('Customers',
    sa.Column('CustomerID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('Name', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('Phone', sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Email', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('CreatedAt', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('CustomerID', name='PK__Customer__A4AE64B8308D3C2B')
    )
    op.create_table('OrderDetails',
    sa.Column('OrderDetailID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('OrderID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ItemID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ItemID'], ['SushiItems.ItemID'], name='FK__OrderDeta__ItemI__4222D4EF'),
    sa.ForeignKeyConstraint(['OrderID'], ['Orders.OrderID'], name='FK__OrderDeta__Order__412EB0B6'),
    sa.PrimaryKeyConstraint('OrderDetailID', name='PK__OrderDet__D3B9D30C50B035B8')
    )
    op.drop_table('order_details')
    op.drop_table('orders')
    op.drop_table('sushi_items')
    op.drop_table('customers')
    # ### end Alembic commands ###
