@startuml UseCase_SushiRestaurant

left to right direction
actor "Customer" as C
actor "Staff" as S

rectangle "Sushi Restaurant Management System" {

  (Register Account) as UC1
  (View Sushi Menu) as UC2
  (Place Order) as UC3
  (View Order Details) as UC4

  (Manage Customers) as UC5
  (Manage Sushi Items) as UC6
  (Manage Orders) as UC7
  (Manage Order Details) as UC8
}

C --> UC1
C --> UC2
C --> UC3
C --> UC4

S --> UC5
S --> UC6
S --> UC7
S --> UC8

note right of UC1
  Customer can:
  - Create new account
  - Provide name & email
  - Stored in Customer table
end note

note right of UC2
  Customer can:
  - Browse sushi items
  - View name, price, category, description
  - No login required
end note

note right of UC3
  Customer can:
  - Select items from menu
  - Confirm order
  - Order stored in Order table
end note

note right of UC4
  Customer can:
  - Track order status
  - View details of items and quantities
  - Linked with OrderDetail
end note

note right of UC5
  Staff can:
  - Add, update, delete customers
  - Correct customer information
end note

note right of UC6
  Staff can:
  - Add new sushi item
  - Update item (name, price, category, description)
  - Delete item
end note

note right of UC7
  Staff can:
  - View all orders
  - Update order status (pending, completed, cancelled)
  - Delete order if needed
end note

note right of UC8
  Staff can:
  - Manage items inside each order
  - Adjust quantity
  - Link sushi items to orders
end note

@enduml